driver=org.postgresql.Driver
url=jdbc:postgresql://localhost:${POSTGRES_PORT}/airline_db
username=${POSTGRES_USER}
password=${POSTGRES_PASSWORD}

changeLogFile=changelog-master.yaml

logLevel=info
classpath=./drivers/postgresql-42.6.0.jar
